name: Windows exe installer build

on:
  push:
    branches: [ main, actions ]
  workflow_dispatch:
    

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download Wix
      uses: i3h/download-release-asset@v1
      with:
        owner: wixtoolset
        repo: wix3
        tag: wix3112rtm
        file: wix311-binaries.zip
    - name: Decompress Wix
      uses: DuckSoft/extract-7z-action@v1.0
      with:
        pathSource: wix311-binaries.zip
        pathTarget: ./target/wix
    - name: Add Wix to Path
      run: echo "$HOME/target/wix" >> $GITHUB_PATH
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B "-Djar.finalName=FNFForwardLauncher" package --file pom.xml
    - name: Package to exe
      run: jpackage --input ./target/ --name FNF-Forward-Launcher --main-jar FNFForwardLauncher.jar --type exe
    - uses: actions/upload-artifact@v2
      with:
        name: windows exe installer
        path: ./FNF-Forward-Launcher*.exe
